--Query para verificar si el Standby esta sincronizado.
--Elaborado por: ByteCodeSolutions
SELECT DISTINCT ARCH.THREAD# "Thread",
  ARCH.SEQUENCE# "PRD_SEQ",
  APPL.SEQUENCE# "STBY_SEQ_APPLY",
 (ARCH.SEQUENCE# - APPL.SEQUENCE#) "SEQ_PENDIENTES"
FROM
(SELECT DISTINCT THREAD# ,SEQUENCE# FROM V$ARCHIVED_LOG WHERE (THREAD#,FIRST_TIME ) IN (SELECT THREAD#,MAX(FIRST_TIME) FROM V$ARCHIVED_LOG GROUP BY THREAD#)) ARCH,
(SELECT DISTINCT THREAD# ,SEQUENCE# FROM V$LOG_HISTORY WHERE (THREAD#,FIRST_TIME ) IN (SELECT THREAD#,MAX(FIRST_TIME) FROM V$LOG_HISTORY GROUP BY THREAD#)) APPL
WHERE
ARCH.THREAD# = APPL.THREAD#
ORDER BY 1;